default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT") %>
  host: <%= ENV.fetch("DB_HOSTNAME") %>

development:
  <<: *default
  database: task_management_development

test:
  <<: *default
  database: task_management_test

production:
  adapter: postgresql
  database: task_management_production
  encoding: unicode